version: '3.8'
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: clients-backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    networks:
      - clients-network

  webserver:
    image: nginx:1.20-alpine
    container_name: clients-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - clients-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: clients-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000/api/clients
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - clients-network

  db:
    image: mysql:5.7
    container_name: clients-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lumen
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - clients-network

networks:
  clients-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
